uploads = []

[[generated]]
id = "P3yU_h-44XnrUUDaqW-67"
uri = "file://attached_assets/generated_images/sehvi_sedzda.png"
type = "image"
title = "sehvi sedzda prayer"

[[generated]]
id = "zp53JHSVlkH9weAyODPgm"
uri = "file://attached_assets/generated_images/prispijevanje_dzemat.png"
type = "image"
title = "joining congregational prayer"

[[generated]]
id = "6Ft_mu2Icx0GLXs2rteDP"
uri = "file://attached_assets/generated_images/cistoca_higijena.png"
type = "image"
title = "cleanliness hygiene"

[[generated]]
id = "f3Zo3zj8fvykSXt5VsmDq"
uri = "file://attached_assets/generated_images/zdrava_ishrana.png"
type = "image"
title = "healthy eating family"

[[generated]]
id = "iBoq8wOS6bfKYTQVYRDwP"
uri = "file://attached_assets/generated_images/ponasanje_jelo.png"
type = "image"
title = "table manners eating"

[[generated]]
id = "hGUjnq8Qv51U58WuvihRj"
uri = "file://attached_assets/generated_images/dova_jelo.png"
type = "image"
title = "prayer after meal"

[[generated]]
id = "H4LmLt12TioBWczaltBqJ"
uri = "file://attached_assets/generated_images/paznja_braca.png"
type = "image"
title = "siblings caring"

[[generated]]
id = "Mc9HJelY9BTtB1o6VvqDL"
uri = "file://attached_assets/generated_images/namaz_cuva.png"
type = "image"
title = "prayer protects"

[[generated]]
id = "9djMmVpBLceSTOh69F1QT"
uri = "file://attached_assets/generated_images/mesh_mestve.png"
type = "image"
title = "wiping over socks"

[[generated]]
id = "XegRE18UzW_yKjMiVgbYe"
uri = "file://attached_assets/generated_images/veliki_grijesi.png"
type = "image"
title = "major sins paths"

[[generated]]
id = "rkHKhQRmQu5srmS5KTCuw"
uri = "file://attached_assets/generated_images/teski_grijesi.png"
type = "image"
title = "grave sins chains"

[[generated]]
id = "m49hPjZIwYltJ_DZ7zM4Y"
uri = "file://attached_assets/generated_images/posljedice_grijeha.png"
type = "image"
title = "consequences of sin"

[[generated]]
id = "ntFJtI4sKan8YQbmvHc9u"
uri = "file://attached_assets/generated_images/cestitost.png"
type = "image"
title = "honesty responsibility"

[[generated]]
id = "ore9ljkT6ZgN-A9IvaKiQ"
uri = "file://attached_assets/generated_images/namaz_bolesnika.png"
type = "image"
title = "prayer of sick person"

[[generated]]
id = "FyTM6caZ4kBhdbuC__fBf"
uri = "file://attached_assets/generated_images/kunut_dova.png"
type = "image"
title = "qunut supplication dawn"

[[generated]]
id = "5qryv322ZfzwiiWCbRfFD"
uri = "file://attached_assets/generated_images/namaska_dova.png"
type = "image"
title = "post prayer supplication"

[[generated]]
id = "bAh-CJdsC3KJs5Lte6JOl"
uri = "file://attached_assets/generated_images/radne_navike.png"
type = "image"
title = "work habits studying"

[[generated]]
id = "iVrLdytQ8WGhewA66ktyp"
uri = "file://attached_assets/generated_images/srednji_put.png"
type = "image"
title = "middle path moderation"

[[generated]]
id = "WKo4WRqbzZNMLr50QlF83"
uri = "file://attached_assets/generated_images/teravih_namaz.png"
type = "image"
title = "tarawih prayer ramadan"

[[generated]]
id = "SapdCH-Z1eWjbKiyDqrpI"
uri = "file://attached_assets/generated_images/istina.png"
type = "image"
title = "power of truth"

[[generated]]
id = "M7KlIGLBtjEaOTPp5LR5y"
uri = "file://attached_assets/generated_images/prevara_laz.png"
type = "image"
title = "deception lies theft"

[[generated]]
id = "8ZWZ6vjCGmaSqT6PMY_7R"
uri = "file://attached_assets/generated_images/ponasanje_drustvo.png"
type = "image"
title = "social gathering behavior"

[[generated]]
id = "A82Rr1QnsjDKWw2p02UhH"
uri = "file://attached_assets/generated_images/kultura_tradicija.png"
type = "image"
title = "bosnian culture tradition"

[[generated]]
id = "qoIkBC9OQa8CLH287VEdE"
uri = "file://attached_assets/generated_images/bosnjak.png"
type = "image"
title = "bosniak identity pride"

[[generated]]
id = "5wDjbNn-xKpxrEkWwRFy8"
uri = "file://attached_assets/generated_images/lekad_dzaekum.png"
type = "image"
title = "quran recitation study"

[[generated]]
id = "zQe6z1fDXauU3HoCNTTjB"
uri = "file://attached_assets/generated_images/sehvi_sedzda_v2.png"
type = "image"
title = "sehvi sedzda prostration"

[[generated]]
id = "MAiaRDONEhj4tOA5f3XEl"
uri = "file://attached_assets/generated_images/prispijevanje_dzemat_v2.png"
type = "image"
title = "joining prayer congregation"

[[generated]]
id = "UxFkn6YlvJowkTAmLHxvi"
uri = "file://attached_assets/generated_images/prispijevanje_dzemat_v3.png"
type = "image"
title = "boy arriving late prayer"

[[generated]]
id = "bF_LlajD8u-kMZKblJc8O"
uri = "file://attached_assets/generated_images/adem_as.png"
type = "image"
title = "paradise garden adam eve"

[[generated]]
id = "2SldomUaJMvi5pNIq7QB4"
uri = "file://attached_assets/generated_images/sifatuz_zatijje.png"
type = "image"
title = "divine essential attributes"

[[generated]]
id = "-rKACLcnU4mnk2eNwmtKn"
uri = "file://attached_assets/generated_images/sifatus_subutijje.png"
type = "image"
title = "divine affirmative attributes"

[[outputs]]
id = "70fM7x_DVtCcdVseXrONt"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/slogovi/d983a102c1a8.mp3"
type = "audio"
title = "بَ (BE)"

[[outputs]]
id = "AkZHt3JXgmPn4K7YCA2Io"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/slogovi/dafee7ba9ab6.mp3"
type = "audio"
title = "جَ (DŽE)"

[[outputs]]
id = "oUDwLQ5fXDIWu996ccT0E"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/slogovi/dc317354e853.mp3"
type = "audio"
title = "بَحَثَ (BE-HA-SE)"

[[outputs]]
id = "lh3OevMsoTmVfh61behbb"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/sample_ghaida.mp3"
type = "audio"
title = "Ghaida — Prijatna, šarmantna i brižna"

[[outputs]]
id = "eyBsM0UdznJzpP9EnQOfG"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/sample_asmaa.mp3"
type = "audio"
title = "Asmaa — Smirena, ohrabrujuća i jasna"

[[outputs]]
id = "fX36dxJYe9wIbXTzLOCiT"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/sample_habibah.mp3"
type = "audio"
title = "Habibah — Izražajna, jasna i topla"

[[outputs]]
id = "y_Q_jkyDqEUPPSQGrbrWK"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/sample_salma.mp3"
type = "audio"
title = "Salma — Pozitivna, profesionalna i topla"

[[outputs]]
id = "_77eCHT7ZZrJdpHfT6VMk"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/preview_yousuf_be.mp3"
type = "audio"
title = "Yousuf — بَ (BE)"

[[outputs]]
id = "uT4bhq4lHWwg9qpXKIA65"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/preview_yousuf_dze.mp3"
type = "audio"
title = "Yousuf — جَ (DŽE)"

[[outputs]]
id = "xnmwiE6CC6kMEAm9Nb4U0"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/preview_yousuf_behase.mp3"
type = "audio"
title = "Yousuf — بَحَثَ (BE-HA-SE)"

[[outputs]]
id = "pEM9BrmiO6Tq5SKxYGmKE"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_sarah_ha.mp3"
type = "audio"
title = "Sarah — حَ (HA)"

[[outputs]]
id = "05vQqiWrhln7xusH9Hfc5"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_sarah_hi.mp3"
type = "audio"
title = "Sarah — حِ (HI)"

[[outputs]]
id = "ircox1dbCzgBGPVwN-BwH"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_sarah_dze.mp3"
type = "audio"
title = "Sarah — جَ (DŽE)"

[[outputs]]
id = "TU4BqvNi5TZ5W368W0cPI"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_sarah_dzu.mp3"
type = "audio"
title = "Sarah — جُ (DŽU)"

[[outputs]]
id = "UzyT4bym-YtJJojwHVggU"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_sara_ha.mp3"
type = "audio"
title = "Sara — حَ (HA)"

[[outputs]]
id = "0sI-K4w33FxYkxmJT4bZg"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_sara_hi.mp3"
type = "audio"
title = "Sara — حِ (HI)"

[[outputs]]
id = "Q9xGsomJ1Gb-Y4GkaTZM4"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_sara_dze.mp3"
type = "audio"
title = "Sara — جَ (DŽE)"

[[outputs]]
id = "v0dCUGrjcAZUPBRmPddAm"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_sara_dzu.mp3"
type = "audio"
title = "Sara — جُ (DŽU)"

[[outputs]]
id = "hOMsfx6LAPbdEYj0OdNRc"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_novi_ha.mp3"
type = "audio"
title = "David Martin 2 — حَ (HA)"

[[outputs]]
id = "OnI3OF570_YbgJpyREKzw"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_novi_hi.mp3"
type = "audio"
title = "David Martin 2 — حِ (HI)"

[[outputs]]
id = "-W1hOL6j3d9weCwk_sf--"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_novi_dze.mp3"
type = "audio"
title = "David Martin 2 — جَ (DŽE)"

[[outputs]]
id = "3pMXl9WhSyI8jJqt2IJpi"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/probe_novi_dzu.mp3"
type = "audio"
title = "David Martin 2 — جُ (DŽU)"

[[outputs]]
id = "Ixjw1JzWXtRWgMV4pvnY7"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/dm2_marhaba.mp3"
type = "audio"
title = "David Martin 2 — مَرْحَبًا (merhaba)"

[[outputs]]
id = "Hrb0dDYIwMXVZ6NvLv2hm"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/dm2_kitab.mp3"
type = "audio"
title = "David Martin 2 — كِتَابౌ (kitab - knjiga)"

[[outputs]]
id = "W77w6RJp_qYnRNtE2QVlM"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/dm2_madrasa.mp3"
type = "audio"
title = "David Martin 2 — مَدْرَسَةౌ (madrasa - škola)"

[[outputs]]
id = "q-bBSsAAcoD_2m0hQaZtz"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/dm2_rasul.mp3"
type = "audio"
title = "David Martin 2 — رَسُولౌ (rasul - poslanik)"

[[outputs]]
id = "tQc0CP5JHuk1lWjAu8cVA"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/dm2_bismillah.mp3"
type = "audio"
title = "David Martin 2 — بِسْمِ اللَّهِ (bismillah)"

[[outputs]]
id = "F-lVngQ49CODcGGGl50OX"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/novi_ha.mp3"
type = "audio"
title = "حَ (HA)"

[[outputs]]
id = "c4w6hzrkEVQ0SYvrPD_iB"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/novi_hi.mp3"
type = "audio"
title = "حِ (HI)"

[[outputs]]
id = "c8n425DaWjEuYftCZoqJK"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/novi_dze.mp3"
type = "audio"
title = "جَ (DŽE)"

[[outputs]]
id = "W11GQXy_X0jkGBNVYZplQ"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/novi_dzu.mp3"
type = "audio"
title = "جُ (DŽU)"

[[outputs]]
id = "lRLZ5X9ZaYW6yR2ThRSiP"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/novi_marhaba.mp3"
type = "audio"
title = "مَرْحَبًا (merhaba)"

[[outputs]]
id = "b5QOcvA8ZL8YB6UjKOote"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/novi_bismillah.mp3"
type = "audio"
title = "بِسْمِ اللَّهِ (bismillah)"

[[outputs]]
id = "hDwh0EcbrKxuXdef_Rx3Z"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/anas_ha.mp3"
type = "audio"
title = "Anas — حَ (HA)"

[[outputs]]
id = "CVEbr4RvWYTRWYRa8DncL"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/anas_hi.mp3"
type = "audio"
title = "Anas — حِ (HI)"

[[outputs]]
id = "Tm82eLTWM_C5aisvCXF2d"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/anas_dze.mp3"
type = "audio"
title = "Anas — جَ (DŽE)"

[[outputs]]
id = "SNPn8RF9iYoJUMuhum14Y"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/anas_dzu.mp3"
type = "audio"
title = "Anas — جُ (DŽU)"

[[outputs]]
id = "Oz5AsUN_k99fRa-t7DcLx"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/anas_marhaba.mp3"
type = "audio"
title = "Anas — مَرْحَبًا (merhaba)"

[[outputs]]
id = "Wcmk9v0t4Xaafl8JKimVj"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/anas_bismillah.mp3"
type = "audio"
title = "Anas — بِسْمِ اللَّهِ (bismillah)"

[[outputs]]
id = "m3uKO4gUfov8LXETCMG8n"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/bs_test_narator_brian.mp3"
type = "audio"
title = "Narator (Brian) — opisni tekst"

[[outputs]]
id = "7Kv4vJ5cHbuhlEu4FK8qC"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/bs_test_dzana_alice.mp3"
type = "audio"
title = "Džana (Alice) — dijalog"

[[outputs]]
id = "rea6wkwu5_2aYaA1oiUzD"
uri = "file://artifacts/mekteb-arapsko-pismo/public/audio/bs_test_amir_liam.mp3"
type = "audio"
title = "Amir (Liam) — dijalog"
