export const RJECNIK: Record<string, string> = {
  "abdest": "Vjersko pranje čistom vodom radi obavljanja namaza ili dodirivanja Kur'ana.",
  "abdesthana": "Posebna prostorija ili mjesto namijenjeno za uzimanje abdesta.",
  "adem": "Prvi čovjek i prvi Božiji poslanik na Zemlji.",
  "ahiret": "Budući svijet, vječni život nakon smrti na ovom svijetu.",
  "ahlak": "Islamsko učenje o lijepom ponašanju i plemenitim osobinama.",
  "ajet": "Rečenica ili kraći tekst u Kur'anu.",
  "akaid": "Nauka o temeljima islamskog vjerovanja.",
  "akika": "Kurban koji se kolje povodom rođenja djeteta.",
  "alim": "Učen čovjek, stručnjak u poznavanju islamskih nauka.",
  "arefat": "Brdo i ravnica blizu Mekke gdje se obavlja ključni obred hadža.",
  "ašere": "Deset odabranih ajeta koji se uče u posebnim prilikama.",
  "ateizam": "Poricanje postojanja Boga i bilo kakvog božanstva.",
  "ashab": "Savremenik i prijatelj Muhammeda, a.s., koji je vjerovao u njega.",
  "avret": "Dio tijela koji musliman i muslimanka moraju pokriti pred drugima.",
  "azhar": "El-Azhar, čuveni islamski univerzitet u Kairu.",
  "azrail": "Melek smrti koji je zadužen za uzimanje duša prilikom umiranja.",
  "buhari": "Imam Buhari, autor najpoznatije i najvjerodostojnije zbirke hadisa.",
  "bajrak": "Zastava, simbol jedinstva i identiteta zajednice.",
  "bajram": "Veliki muslimanski blagdan (Ramazanski i Kurban-bajram).",
  "bedel": "Osoba koja umjesto drugoga obaviti hadž ako on to nije u stanju.",
  "bedr": "Mjesto prve velike bitke u historiji islama.",
  "bejtullah": "Allahova kuća, naziv za Kabu u Mekki.",
  "bejtul-mal": "Državna blagajna ili zajednička imovina muslimana.",
  "berzah": "Stanje u kaburu između smrti i Sudnjeg dana.",
  "bid'at": "Novotarija u vjeri koja nema utemeljenje u izvorima islama.",
  "bismilla": "Rečenica kojom se započinje svaki koristan posao ('U ime Allaha').",
  "burak": "Nebesko biće na kojem je Poslanik, a.s., putovao tokom Miradža.",
  "daif": "Slab, oznaka za hadis čija vjerodostojnost nije na najvišem nivou.",
  "daija": "Osoba koja poziva druge ljude u vjeru islam.",
  "da'va": "Pozivanje i podučavanje ljudi vjeri islamu.",
  "da'vet": "Pozivanje i podučavanje ljudi vjeri islamu.",
  "dedžal": "Lažni mesija koji će se pojaviti pred kraj svijeta da zavodi ljude.",
  "ders": "Predavanje, lekcija ili pouka o vjeri.",
  "derviš": "Osoba koja se posvetila duhovnom uzdizanju i spominjanju Allaha.",
  "din": "Vjera, put ili sam islam kao vjerski sistem.",
  "dova": "Molba upućena Allahu, dž.š., za dobro na oba svijeta.",
  "dunja": "Ovaj, prolazni svijet na kojem sada živimo.",
  "dunjaluk": "Ovaj, prolazni svijet na kojem sada živimo.",
  "džahil": "Neznalica, osoba koja ne poznaje propise vjere ili se loše ponaša.",
  "dženaza": "Namaz i obred ispraćaja umrle osobe.",
  "džihad": "Trud i borba na Allahovom putu radi postizanja dobra.",
  "džini": "Nevidljiva bića stvorena od vatre koja imaju slobodnu volju.",
  "džennet": "Raj, mjesto vječne nagrade i uživanja za vjernike.",
  "džehennem": "Pakao, mjesto kazne za nevjernike i grješnike.",
  "džuz": "Trideseti dio Kur'ana koji se sastoji od dvadeset stranica.",
  "ebu hanife": "Osnivač hanefijskog mezheba, poznat kao 'Veliki imam'.",
  "ebu jusuf": "Jedan od najpoznatijih učenika imama Ebu Hanife.",
  "ebu bekr": "Prvi pravedni halifa i najbliži prijatelj Poslanika, a.s.",
  "ebu leheb": "Poslanikov amidža koji je bio veliki protivnik islama.",
  "edeb": "Islamski bonton, pristojnost i lijepo ophođenje prema drugima.",
  "efendija": "Počasni naziv za imama ili obrazovanu osobu.",
  "ehli kitab": "Sljedbenici Knjige (Jevreji i Kršćani).",
  "ehli sunnet": "Većinska grupa muslimana koja slijedi sunnet Poslanika, a.s.",
  "ehli bejt": "Uža porodica Muhammeda, a.s.",
  "ensarija": "Stanovnik Medine koji je pomogao muslimanima iz Mekke.",
  "esmaul-husna": "Lijepa Allahova imena kojih ima devedeset i devet.",
  "etika": "Nauka o moralu i ispravnom djelovanju.",
  "euzubilla": "Rečenica kojom tražiti Allahovu zaštitu od šejtana.",
  "ezan": "Poziv na namaz koji se uči s minareta džamije.",
  "farz": "Stroga vjerska obaveza koju je Allah, dž.š., naredio.",
  "farz ajn": "Obaveza koja se odnosi na svakog pojedinca lično.",
  "farz kifaje": "Zajednička obaveza koju ako obavi dio grupe, ostali su slobodni.",
  "fatima": "Najmlađa kći Poslanika Muhammeda, a.s., i supruga Alije, r.a.",
  "fetva": "Pravno rješenje ili odgovor na vjersko pitanje koje daje muftija.",
  "fidija": "Otkupnina u novcu ili hrani za propuštene dane posta.",
  "fikh": "Islamsko pravo, nauka o vjerskim propisima i obredima.",
  "gajb": "Nevidljivi svijet, ono što je sakriveno od ljudskih čula.",
  "gasul": "Vjersko kupanje i opremanje umrle osobe.",
  "gusul": "Vjersko kupanje cijelog tijela radi postizanja potpune čistoće.",
  "hadidža": "Prva supruga Muhammeda, a.s., i prva vjernica u islamu.",
  "hatidža": "Prva supruga Muhammeda, a.s., i prva vjernica u islamu.",
  "hadis": "Govor, djelo ili odobrenje Muhammeda, a.s.",
  "hadisi kudsijj": "Hadis u kojem Poslanik, a.s., prenosi Allahove riječi.",
  "hadžerul-esved": "Crni kamen ugrađen u jedan ugao Kabe.",
  "hadž": "Hodočašće Kabi u Mekki, jedan od islamskih šartova.",
  "hadžija": "Osoba koja je obavila propise hadža.",
  "hafiz": "Osoba koja zna cijeli Kur'an napamet.",
  "hajz": "Mjesečni ciklus kod žena sa posebnim vjerskim propisima.",
  "halal": "Sve što je dozvoljeno i čisto prema islamskim propisima.",
  "halifa": "Nasljednik Poslanika, a.s., u vođenju muslimanske zajednice.",
  "hanefijski mezheb": "Jedna od četiri pravne škole u islamu koju slijede Bošnjaci.",
  "haram": "Sve što je strogo zabranjeno prema islamskim propisima.",
  "harem": "Sveti i zaštićeni prostor oko džamije ili Kabe.",
  "haremi-šerif": "Naziv za prostor oko Kabe u Mekki ili džamije u Medini.",
  "harf": "Slovo arapskog pisma kojim je napisan Kur'an.",
  "hatib": "Osoba koja govori hutbu na džuma-namazu.",
  "hatma": "Pročitati cijeli Kur'an od početka do kraja.",
  "hava": "Prva žena na svijetu i supruga Adema, a.s.",
  "hedija": "Poklon koji se daje dragoj osobi radi jačanja ljubavi.",
  "hidžab": "Odjeća muslimanke koja ispunjava propise o pokrivanju tijela.",
  "hidžra": "Seoba muslimana iz Mekke u Medinu 622. godine.",
  "hilafet": "Institucija halife i način vođenja islamske države.",
  "hira": "Pećina blizu Mekke u kojoj je počela objava Kur'ana.",
  "hutba": "Govor koji imam drži s minbera tokom džume ili bajrama.",
  "hulefairašidin": "Četvorica pravednih halifa (Ebu Bekr, Omer, Osman i Alija).",
  "ibadet": "Svako dobro djelo kojim se stječe Allahovo zadovoljstvo.",
  "iblis": "Šejtan, biće koje zavodi ljude na pogrešan put.",
  "ibn kesir": "Autor jednog od najpoznatijih tumačenja (tefsira) Kur'ana.",
  "ibrahim": "Božiji poslanik, praotac monoteističkih religija.",
  "iddet": "Vrijeme čekanja za ženu nakon razvoda ili smrti muža.",
  "iftar": "Obrok kojim se završava dnevni post nakon zalaska sunca.",
  "ihram": "Posebna odjeća i stanje tokom obavljanja hadža ili umre.",
  "ihlas": "Iskrenost u vjeri i naziv 112. kur'anske sure.",
  "ikamet": "Poziv koji se uči neposredno pred početak farz namaza.",
  "ilum": "Znanje i nauka u najširem smislu.",
  "imam": "Osoba koja predvodi muslimane u namazu ili zajednici.",
  "iman": "Čvrsto vjerovanje u šest imanskih šartova.",
  "imsak": "Vrijeme prestanka jela i pića i početak dnevnog posta.",
  "indžil": "Sveta knjiga objavljena poslaniku Isau, a.s.",
  "inšallah": "Izraz koji znači 'ako Bog dade'.",
  "isa": "Božiji poslanik rođen od Merjeme bez oca.",
  "ishak": "Sin poslanika Ibrahima i praotac mnogih poslanika.",
  "islam": "Predanost i pokornost Jednom Bogu, Allahu, dž.š.",
  "ismail": "Prvi sin poslanika Ibrahima s kojim je gradio Kabu.",
  "isra": "Noćno putovanje Poslanika, a.s., od Mekke do Jerusalema.",
  "istihaza": "Krvarenje kod žena koje nije hajz ni nifas.",
  "istigfar": "Tražiti oprost od Allaha izgovaranjem 'Estagfirullah'.",
  "istihara": "Namaz i dova kojom tražiti Allahovu uputu pri donošenju odluke.",
  "itikaf": "Boravak u džamiji zadnjih deset dana ramazana radi ibadeta.",
  "jasin": "Jedna od najpoznatijih sura u Kur'anu.",
  "jesrib": "Stari naziv za grad Medinu prije dolaska muslimana.",
  "kaba": "Sveti hram u Mekki prema kojem se okrećemo u namazu.",
  "kabur": "Grob, mjesto u koje se polaže tijelo umrle osobe.",
  "kader": "Allahovo određenje svega što se događa u svemiru.",
  "kadei-ehire": "Posljednje sjedenje u namazu radi predaje selama.",
  "kafir": "Nevjernik, osoba koja ne vjeruje u Allaha ili poriče istinu.",
  "kasida": "Vrsta pobožne pjesme koja slavi vjeru.",
  "kelimei-šehadet": "Rečenica kojom se izražava pripadnost islamu.",
  "kibla": "Smjer prema Kabi u Mekki.",
  "kijam": "Stajanje u namazu.",
  "kijamet": "Sudnji dan, kraj ovog svijeta i početak vječnog života.",
  "kiraet": "Učenje Kur'ana, posebno tokom obavljanja namaza.",
  "kitab": "Knjiga, često se misli na Kur'an ili druge objave.",
  "kufr": "Nevjerovanje ili poricanje Allahove istine.",
  "kur'an": "Posljednja Božija objava poslana cijelom čovječanstvu.",
  "kurban": "Žrtva koja se kolje u ime Allaha radi približavanja Njemu.",
  "lejletul-kadr": "Noć Sudbine, najvrednija noć u godini u mjesecu ramazanu.",
  "lejletul-miradž": "Noć u kojoj je Poslanik, a.s., uzdignut do Allaha.",
  "magrib": "Zapad, vrijeme zalaska sunca i akšam-namaza.",
  "medresa": "Škola u kojoj se stječe srednje islamsko obrazovanje.",
  "mehr": "Vjenčani dar koji muž daje supruzi.",
  "mekruh": "Nešto što je pokuđeno i što je bolje izbjegavati.",
  "mekruh tenzihen": "Lakši oblik pokuđenosti.",
  "mekruh tahrimen": "Teži oblik pokuđenosti koji je blizu harama.",
  "melek": "Duhovno biće stvoreno od svjetlosti koje sluša Allaha.",
  "mendub": "Djelo koje je lijepo i pohvalno uraditi.",
  "mevlud": "Rođenje Muhammeda, a.s., i svečanost tim povodom.",
  "mezheb": "Pravna škola ili pravac u tumačenju propisa.",
  "mezar": "Grob, mjesto ukopa umrle osobe.",
  "mihrab": "Mjesto u džamiji koje pokazuje smjer kible.",
  "mikat": "Mjesto na kojem hadžije oblače ihrame.",
  "minber": "Uzvišeno mjesto u džamiji s kojeg imam drži hutbu.",
  "miradž": "Putovanje Muhammeda, a.s., kroz nebeska prostranstva.",
  "muallim": "Vjeroučitelj ili vjeroučiteljica u mektebu.",
  "mubah": "Djelo koje je dozvoljeno i neutralno.",
  "mudžiza": "Nadnaravna pojava kojom Allah potvrđuje poslanike.",
  "mufsid": "Djelo koje kvari ili poništava ispravnost obreda.",
  "muhaddis": "Učenjak koji se bavi izučavanjem hadisa.",
  "muhadžir": "Iseljenik koji je radi vjere napustio svoj dom.",
  "muftija": "Vjerski autoritet ovlašten za izdavanje fetvi.",
  "mukabela": "Zajedničko učenje Kur'ana tokom ramazana.",
  "muktedija": "Osoba koja klanja namaz prateći imama.",
  "munafik": "Licemjer, osoba koja skriva nevjerstvo a pokazuje vjeru.",
  "musafir": "Osoba koja se nalazi na putovanju.",
  "mushaf": "Zapisani tekst cijelog Kur'ana u obliku knjige.",
  "mustehab": "Djelo koje je lijepo i pohvalno činiti.",
  "namaz": "Islamska molitva — jedan od pet stubova islama.",
  "nifak": "Licemjerstvo, pretvaranje u vjeri.",
  "nifas": "Krvarenje kod žena nakon porođaja.",
  "nisab": "Određena količina imovine na koju se daje zekat.",
  "nišan": "Nadgrobni spomenik specifičnog izgleda kod muslimana.",
  "nijet": "Namjera — ibadet bez nijeta nije ispravno primljen.",
  "omer ibn hattab": "Drugi pravedni halifa poznat po svojoj pravednosti.",
  "osman ibn affan": "Treći pravedni halifa poznat po darežljivosti.",
  "rabb": "Gospodar, Stvoritelj i Održavatelj svega.",
  "ramazan": "Deveti mjesec islamskog kalendara i mjesec posta.",
  "resulullah": "Allahov Poslanik, naziv za Muhammeda, a.s.",
  "rekat": "Jedan ciklus radnji u namazu.",
  "rijaset": "Vrhovno tijelo i uprava Islamske zajednice.",
  "ruku": "Pregibanje u namazu sa dlanovima na koljenima.",
  "sabah": "Jutro, vrijeme svitanja i prvog dnevnog namaza.",
  "sadakatul-fitr": "Milostinja koja se daje siromašnima uz ramazan.",
  "sadaka": "Dobrovoljni prilog — svako dobro djelo računa se kao sadaka.",
  "saff": "Red klanjača koji stoje jedan do drugog.",
  "safa i merva": "Dva brežuljka u Mekki između kojih se kreću hadžije.",
  "sahibi-uzur": "Osoba koja ima stalnu fizičku zapreku za obrede.",
  "sahih": "Vjerodostojan i ispravan (hadis ili obred).",
  "saj": "Užurbani hod između Safe i Merve.",
  "salavat": "Molitva i blagoslov za Muhammeda, a.s.",
  "sedžada": "Prostirač na kojem se obavlja namaz.",
  "sedžda": "Spuštanje lica na tlo u namazu radi pokornosti Allahu.",
  "sedždei-tilavet": "Sedžda koja se čini zbog određenih ajeta u Kur'anu.",
  "sehur": "Obrok pred zoru kojim počinje dnevni post.",
  "sehvi-sedžda": "Dvije sedžde na kraju namaza zbog nehotične greške.",
  "sifat": "Svojstvo ili osobina.",
  "sifati-zatijje": "Allahova svojstva koja pripadaju samo Njemu.",
  "sifati-subutijje": "Allahova svojstva koja se u tragovima nalaze kod stvorenja.",
  "sira": "Životopis Muhammeda, a.s.",
  "sufara": "Priručnik za učenje arapskog pisma i čitanja Kur'ana.",
  "sunet": "Obrezivanje muške djece radi higijene i tradicije.",
  "sunnet": "Sve što je Poslanik, a.s., radio, govorio ili preporučio.",
  "sunnet muekkede": "Pritvrđeni sunnet koji je Poslanik stalno činio.",
  "sunnet gajri muekkede": "Nepritvrđeni sunnet koji je Poslanik povremeno činio.",
  "sura": "Poglavlje u Kur'anu kojih ima ukupno stotinu i četrnaest.",
  "šart": "Uslov koji mora biti ispunjen za valjanost obreda.",
  "šefaat": "Zauzimanje Poslanika, a.s., za vjernike na Sudnjem danu.",
  "šehadet": "Svjedočenje da je samo Allah Bog i Muhammed Njegov poslanik.",
  "šehid": "Vjernik koji je poginuo braneći vjeru ili domovinu.",
  "šejh": "Učen čovjek ili duhovni vođa.",
  "šerijat": "Islamski zakon utemeljen na Kur'anu i sunnetu.",
  "širk": "Pripisivanje Allahu druga, najveći grijeh.",
  "taharet": "Stanje potpune vjerske i fizičke čistoće.",
  "tavaf": "Obilaženje oko Kabe sedam puta.",
  "tedžvid": "Nauka o pravilnom učenju Kur'ana.",
  "tefsir": "Nauka o tumačenju smisla kur'anskih ajeta.",
  "tejemmum": "Čišćenje čistom zemljom kada nema vode.",
  "tekbir": "Izgovaranje riječi 'Allahu ekber'.",
  "tekbiri-tešrik": "Tekbiri koji se uče tokom Kurban-bajrama.",
  "tespih": "Spominjanje i hvaljenje Allaha određenim riječima.",
  "tevba": "Iskreno pokajanje Allahu za učinjene grijehe.",
  "tevhid": "Vjerovanje u Allahovu jednoću.",
  "ummet": "Zajednica svih muslimana svijeta.",
  "umra": "Posjeta Kabi koja se obavlja izvan vremena hadža.",
  "vadžib": "Vjerska obaveza koja je po rangu odmah ispod farza.",
  "vakuf": "Trajna zadužbina u ime Allaha za opće dobro ljudi.",
  "zekat": "Obavezno davanje dijela imovine siromašnima.",
  "zikr": "Spominjanje Allaha riječima hvale i zahvale.",
  "zuhr": "Podne, vrijeme drugog dnevnog namaza.",
  "mekteb": "Islamska vjeronaučna škola za djecu.",
  "džemat": "Zajednica muslimana koji zajedno klanjaju ili žive.",
  "džamija": "Islamska bogomolja i centar muslimanske zajednice.",
  "sabr": "Strpljenje — jedna od najvažnijih vrlina pravog vjernika.",
  "džuma": "Petak — poseban dan za muslimane sa zajedničkim namazom.",
  "takva": "Bogobojaznost — strah od Allaha i čuvanje od grijeha.",
  "amanet": "Povjerena stvar — svaka dužnost koja nam je povjerena.",
  "tevekkul": "Oslanjanje na Allaha uz vlastiti trud i zalaganje.",
  "hamd": "Zahvala Allahu — Elhamdulillah (Hvala Allahu).",
  "mujezin": "Osoba koja uči ezan s minareta džamije.",
  "poslanik": "Onaj koga Allah šalje kao Svog glasnika — Muhammed, a.s.",
  "adl": "Pravednost — jedan od temeljnih principa islama.",
  "ahkam": "Propisi, šerijatske odredbe koje reguliraju život muslimana.",
  "ahl": "Porodica, ukućani, članovi porodice.",
  "asr": "Ikindija, vrijeme trećeg dnevnog namaza.",
  "barakah": "Berićet, blagoslov koji dolazi od Allaha.",
  "batin": "Skriveni, unutarnji smisao (suprotno od zahir).",
  "darul-islam": "Područje u kojem vladaju islamski propisi.",
  "darvindžija": "Sljedbenik Darvina i teorije evolucije.",
  "dželal": "Allahovo svojstvo veličanstvenosti i moći.",
  "džemal": "Allahovo svojstvo ljepote i milosti.",
  "fajr": "Zora, vrijeme sabah-namaza.",
  "fasik": "Griješnik, osoba koja krši vjerske propise.",
  "firdevs": "Najviši stepen Dženneta.",
  "fitna": "Smutnja, nered i iskušenje u zajednici.",
  "fitr": "Prirodno stanje čistoće s kojim se čovjek rodi.",
  "hajr": "Dobro, dobrobit, svako korisno djelo.",
  "halife": "Zamjenik, namjesnik — vođa muslimanske zajednice.",
  "hamajlija": "Zapis koji se nosi kao zaštita — u islamu je bitno da sadrži dovu.",
  "hasan": "Dobar, oznaka za hadis dobre vjerodostojnosti.",
  "havuz": "Bazen Poslanika, a.s., na Sudnjem danu.",
  "hikmet": "Mudrost, duboko razumijevanje vjere i života.",
  "hudžra": "Soba, prostorija — posebno sobe Poslanikovih žena u Medini.",
  "ihsan": "Najviši stepen vjere — obožavati Allaha kao da Ga vidiš.",
  "iktida": "Pridruživanje imamu u zajedničkom namazu.",
  "ilmihal": "Priručnik s osnovnim znanjima iz islamske vjere.",
  "irdža": "Odgađanje suda o vjerniku koji je počinio grijeh.",
  "ismet": "Bezgrješnost poslanika i njihova zaštićenost od grijeha.",
  "istabraq": "Gusta svila koja se spominje u opisu Dženneta.",
  "jevmud-din": "Dan vjere, Dan obračuna — Sudnji dan.",
  "kafara": "Iskup za prekršeni zakletvu ili propust u ibadetu.",
  "kasr": "Skraćivanje namaza na putovanju.",
  "katl": "Ubistvo, oduzimanje ljudskog života.",
  "kevser": "Džennetsko vrelo koje je obećano Poslaniku, a.s.",
  "kijamulejl": "Noćni namaz, posebno tahajjud namaz.",
  "kurbani vukuf": "Stajanje na Arefatu — ključni obred hadža.",
  "levhi-mahfuz": "Čuvana ploča na kojoj je zapisana sudbina svega.",
  "ma'ruf": "Dobro, ono što je poznato kao ispravno u vjeri.",
  "mahr": "Vjenčani dar koji muž obavezno daje supruzi.",
  "mazlum": "Onaj kome je učinjena nepravda.",
  "mes'ala": "Vjersko pitanje ili pravni problem.",
  "mesdžid": "Mjesto sedžde, manji prostor za namaz.",
  "mešru": "Zakonito, propisano šerijatom.",
  "mevta": "Umrla osoba, mejt.",
  "miras": "Nasljedstvo prema islamskim propisima.",
  "mizan": "Vaga na kojoj će se vagati djela na Sudnjem danu.",
  "mu'min": "Pravi vjernik koji istinski vjeruje srcem i djelima.",
  "munker i nekir": "Dva meleka koji ispituju umrle u kaburu.",
  "musalla": "Otvoreni prostor ili mjesto za obavljanje namaza.",
  "müstehazen": "Ono što se smatra lijepim i pohvalnim.",
  "muštehid": "Učenjak sposoban za samostalno izvođenje propisa iz izvora.",
  "muttefekun alejhi": "Hadis oko čije vjerodostojnosti se slažu Buhari i Muslim.",
  "nafilah": "Dobrovoljni, dodatni ibadet iznad obaveznog.",
  "nedžaset": "Nečistoća koja kvari stanje tahare.",
  "nešr": "Proživljenje mrtvih na Sudnjem danu.",
  "nur": "Svjetlost — Allahovo svojstvo i simbol upute.",
  "ridžal": "Nauka o prenosiocima hadisa.",
  "rija": "Pretvaranje, činjenje ibadeta radi pokazivanja pred ljudima.",
  "rukja": "Učenje Kur'ana ili dove radi liječenja bolesti.",
  "selam": "Pozdrav mira — Esselamu alejkum.",
  "sirat": "Most preko Džehennema koji prelaze svi ljudi na Sudnjem danu.",
  "subhanallah": "Slava Allahu — izraz veličanja i čuđenja.",
  "šukr": "Zahvalnost Allahu na blagodatima.",
  "tabiin": "Generacija muslimana koja je učila od ashaba.",
  "tafakkur": "Razmišljanje i kontemplacija o Allahovim znakovima.",
  "taklid": "Slijeđenje učenja jednog mezheba bez poznavanja dokaza.",
  "tawba": "Pokajanje, vraćanje Allahu nakon grijeha.",
  "telbije": "Dova 'Lebbejk Allahumme lebbejk' koju govore hadžije.",
  "uhud": "Brdo i bitka kod Medine u 3. godini po hidžri.",
  "usuli fikh": "Metodologija islamskog prava.",
  "vitr": "Namaz neparnog broja rekata koji se klanja noću.",
  "veli": "Blizak Allahov rob, prijatelj Allahov.",
  "zahid": "Osoba koja se odrekla dunjalučkih užitaka radi ahireta.",
  "zahir": "Vanjski, očigledni smisao teksta (suprotno od batin).",
  "zalim": "Nasilnik, onaj koji čini nepravdu.",
  "zemzem": "Sveti izvor vode u haremu Kabe u Mekki.",
};
