// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ilmihal-header/Compact.tsx": () => import("../components/mockups/ilmihal-header/Compact.tsx"),
  "./components/mockups/ilmihal-header/Current.tsx": () => import("../components/mockups/ilmihal-header/Current.tsx"),
  "./components/mockups/napamet-pregled/Current.tsx": () => import("../components/mockups/napamet-pregled/Current.tsx"),
  "./components/mockups/napamet-pregled/ProgressiveDisclosure.tsx": () => import("../components/mockups/napamet-pregled/ProgressiveDisclosure.tsx")
};
