const ILMIHAL_RJECNIK = {
    "Abdest": "Vjersko pranje čistom vodom radi obavljanja namaza ili dodirivanja Kur'ana.",
    "Abdesthana": "Posebna prostorija ili mjesto namijenjeno za uzimanje abdesta.",
    "Adem": "Prvi čovjek i prvi Božiji poslanik na Zemlji.",
    "Ahiret": "Budući svijet, vječni život nakon smrti na ovom svijetu.",
    "Ahlak": "Islamsko učenje o lijepom ponašanju i plemenitim osobinama.",
    "Ajet": "Rečenica ili kraći tekst u Kur'anu.",
    "Akaid": "Nauka o temeljima islamskog vjerovanja.",
    "Akika": "Kurban koji se kolje povodom rođenja djeteta.",
    "Alim": "Učen čovjek, stručnjak u poznavanju islamskih nauka.",
    "Arefat": "Brdo i ravnica blizu Mekke gdje se obavlja ključni obred hadža.",
    "Ašere": "Deset odabranih ajeta koji se uče u posebnim prilikama.",
    "Ateizam": "Poricanje postojanja Boga i bilo kakvog božanstva.",
    "Ashab": "Savremenik i prijatelj Muhammeda, a.s., koji je vjerovao u njega.",
    "Avret": "Dio tijela koji musliman i muslimanka moraju pokriti pred drugima.",
    "Azhar": "El-Azhar, čuveni islamski univerzitet u Kairu.",
    "Azrail": "Melek smrti koji je zadužen za uzimanje duša prilikom umiranja.",
    "Buhari": "Imam Buhari, autor najpoznatije i najvjerodostojnije zbirke hadisa.",
    "Bajrak": "Zastava, simbol jedinstva i identiteta zajednice.",
    "Bajram": "Veliki muslimanski blagdan (Ramazanski i Kurban-bajram).",
    "Bedel": "Osoba koja umjesto drugoga obaviti hadž ako on to nije u stanju.",
    "Bedr": "Mjesto prve velike bitke u historiji islama.",
    "Bejtullah": "Allahova kuća, naziv za Kabu u Mekki.",
    "Bejtul-mal": "Državna blagajna ili zajednička imovina muslimana.",
    "Berzah": "Stanje u kaburu između smrti i Sudnjeg dana.",
    "Bid’at": "Novotarija u vjeri koja nema utemeljenje u izvorima islama.",
    "Bismilla": "Rečenica kojom se započinje svaki koristan posao ('U ime Allaha').",
    "Burak": "Nebesko biće na kojem je Poslanik, a.s., putovao tokom Miradža.",
    "Daif": "Slab, oznaka za hadis čija vjerodostojnost nije na najvišem nivou.",
    "Daija": "Osoba koja poziva druge ljude u vjeru islam.",
    "Da’va (Da’vet)": "Pozivanje i podučavanje ljudi vjeri islamu.",
    "Dedžal": "Lažni mesija koji će se pojaviti pred kraj svijeta da zavodi ljude.",
    "Ders": "Predavanje, lekcija ili pouka o vjeri.",
    "Derviš": "Osoba koja se posvetila duhovnom uzdizanju i spominjanju Allaha.",
    "Din": "Vjera, put ili sam islam kao vjerski sistem.",
    "Dova": "Molba upućena Allahu, dž.š., za dobro na oba svijeta.",
    "Dunja (Dunjaluk)": "Ovaj, prolazni svijet na kojem sada živimo.",
    "Džahil": "Neznalica, osoba koja ne poznaje propise vjere ili se loše ponaša.",
    "Dženaza": "Namaz i obred ispraćaja umrle osobe.",
    "Džihad": "Trud i borba na Allahovom putu radi postizanja dobra.",
    "Džini": "Nevidljiva bića stvorena od vatre koja imaju slobodnu volju.",
    "Džennet": "Raj, mjesto vječne nagrade i uživanja za vjernike.",
    "Džehennem": "Pakao, mjesto kazne za nevjernike i grješnike.",
    "Džuz": "Trideseti dio Kur'ana koji se sastoji od dvadeset stranica.",
    "Ebu Hanife": "Osnivač hanefijskog mezheba, poznat kao 'Veliki imam'.",
    "Ebu Jusuf": "Jedan od najpoznatijih učenika imama Ebu Hanife.",
    "Ebu Bekr": "Prvi pravedni halifa i najbliži prijatelj Poslanika, a.s.",
    "Ebu Leheb": "Poslanikov amidža koji je bio veliki protivnik islama.",
    "Edeb": "Islamski bonton, pristojnost i lijepo ophođenje prema drugima.",
    "Efendija": "Počasni naziv za imama ili obrazovanu osobu.",
    "Ehli Kitab": "Sljedbenici Knjige (Jevreji i Kršćani).",
    "Ehli Sunnet": "Većinska grupa muslimana koja slijedi sunnet Poslanika, a.s.",
    "Ehli Bejt": "Uža porodica Muhammeda, a.s.",
    "Ensarija": "Stanovnik Medine koji je pomogao muslimanima iz Mekke.",
    "Esmaul-husna": "Lijepa Allahova imena kojih ima devedeset i devet.",
    "Etika": "Nauka o moralu i ispravnom djelovanju.",
    "Euzubilla": "Rečenica kojom tražiti Allahovu zaštitu od šejtana.",
    "Ezan": "Poziv na namaz koji se uči s minareta džamije.",
    "Farz": "Stroga vjerska obaveza koju je Allah, dž.š., naredio.",
    "Farz ajn": "Obaveza koja se odnosi na svakog pojedinca lično.",
    "Farz kifaje": "Zajednička obaveza koju ako obavi dio grupe, ostali su slobodni.",
    "Fatima": "Najmlađa kći Poslanika Muhammeda, a.s., i supruga Alije, r.a.",
    "Fetva": "Pravno rješenje ili odgovor na vjersko pitanje koje daje muftija.",
    "Fidija": "Otkupnina u novcu ili hrani za propuštene dane posta.",
    "Fikh": "Islamsko pravo, nauka o vjerskim propisima i obredima.",
    "Gajb": "Nevidljivi svijet, ono što je sakriveno od ljudskih čula.",
    "Gasul": "Vjersko kupanje i opremanje umrle osobe.",
    "Gusul": "Vjersko kupanje cijelog tijela radi postizanja potpune čistoće.",
    "Hadidža (Hatidža)": "Prva supruga Muhammeda, a.s., i prva vjernica u islamu.",
    "Hadis": "Govor, djelo ili odobrenje Muhammeda, a.s.",
    "Hadisi kudsijj": "Hadis u kojem Poslanik, a.s., prenosi Allahove riječi.",
    "Hadžerul-esved": "Crni kamen ugrađen u jedan ugao Kabe.",
    "Hadž": "Hodočašće Kabi u Mekki, jedan od islamskih šartova.",
    "Hadžija": "Osoba koja je obavila propise hadža.",
    "Hafiz": "Osoba koja zna cijeli Kur'an napamet.",
    "Hajz": "Mjesečni ciklus kod žena sa posebnim vjerskim propisima.",
    "Halal": "Sve što je dozvoljeno i čisto prema islamskim propisima.",
    "Halifa": "Nasljednik Poslanika, a.s., u vođenju muslimanske zajednice.",
    "Hanefijski mezheb": "Jedna od četiri pravne škole u islamu koju slijede Bošnjaci.",
    "Haram": "Sve što je strogo zabranjeno prema islamskim propisima.",
    "Harem": "Sveti i zaštićeni prostor oko džamije ili Kabe.",
    "Haremi-šerif": "Naziv za prostor oko Kabe u Mekki ili džamije u Medini.",
    "Harf": "Slovo arapskog pisma kojim je napisan Kur'an.",
    "Hatib": "Osoba koja govori hutbu na džuma-namazu.",
    "Hatma": "Pročitati cijeli Kur'an od početka do kraja.",
    "Hava": "Prva žena na svijetu i supruga Adema, a.s.",
    "Hedija": "Poklon koji se daje dragoj osobi radi jačanja ljubavi.",
    "Hidžab": "Odjeća muslimanke koja ispunjava propise o pokrivanju tijela.",
    "Hidžra": "Seoba muslimana iz Mekke u Medinu 622. godine.",
    "Hilafet": "Institucija halife i način vođenja islamske države.",
    "Hira": "Pećina blizu Mekke u kojoj je počela objava Kur'ana.",
    "Hutba": "Govor koji imam drži s minbera tokom džume ili bajrama.",
    "Hulefairašidin": "Četvorica pravednih halifa (Ebu Bekr, Omer, Osman i Alija).",
    "Ibadet": "Svako dobro djelo kojim se stječe Allahovo zadovoljstvo.",
    "Iblis": "Šejtan, biće koje zavodi ljude na pogrešan put.",
    "Ibn Kesir": "Autor jednog od najpoznatijih tumačenja (tefsira) Kur'ana.",
    "Ibrahim": "Božiji poslanik, praotac monoteističkih religija.",
    "Iddet": "Vrijeme čekanja za ženu nakon razvoda ili smrti muža.",
    "Iftar": "Obrok kojim se završava dnevni post nakon zalaska sunca.",
    "Ihram": "Posebna odjeća i stanje tokom obavljanja hadža ili umre.",
    "Ihlas": "Iskrenost u vjeri i naziv 112. kur’anske sure.",
    "Ikamet": "Poziv koji se uči neposredno pred početak farz namaza.",
    "Ilum": "Znanje i nauka u najširem smislu.",
    "Imam": "Osoba koja predvodi muslimane u namazu ili zajednici.",
    "Iman": "Čvrsto vjerovanje u šest imanskih šartova.",
    "Imsak": "Vrijeme prestanka jela i pića i početak dnevnog posta.",
    "Indžil": "Sveta knjiga objavljena poslaniku Isau, a.s.",
    "Inšallah": "Izraz koji znači 'ako Bog dade'.",
    "Isa": "Božiji poslanik rođen od Merjeme bez oca.",
    "Ishak": "Sin poslanika Ibrahima i praotac mnogih poslanika.",
    "Islam": "Predanost i pokornost Jednom Bogu, Allahu, dž.š.",
    "Ismail": "Prvi sin poslanika Ibrahima s kojim je gradio Kabu.",
    "Isra": "Noćno putovanje Poslanika, a.s., od Mekke do Jerusalema.",
    "Istihaza": "Krvarenje kod žena koje nije hajz ni nifas.",
    "Istigfar": "Tražiti oprost od Allaha izgovaranjem 'Estagfirullah'.",
    "Istihara": "Namaz i dova kojom tražiti Allahovu uputu pri donošenju odluke.",
    "Itikaf": "Boravak u džamiji zadnjih deset dana ramazana radi ibadeta.",
    "Jasin": "Jedna od najpoznatijih sura u Kur'anu.",
    "Jesrib": "Stari naziv za grad Medinu prije dolaska muslimana.",
    "Kaba": "Sveti hram u Mekki prema kojem se okrećemo u namazu.",
    "Kabur": "Grob, mjesto u koje se polaže tijelo umrle osobe.",
    "Kader": "Allahovo određenje svega što se događa u svemiru.",
    "Kadei-ehire": "Posljednje sjedenje u namazu radi predaje selama.",
    "Kafir": "Nevjernik, osoba koja ne vjeruje u Allaha ili poriče istinu.",
    "Kasida": "Vrsta pobožne pjesme koja slavi vjeru.",
    "Kelimei-šehadet": "Rečenica kojom se izražava pripadnost islamu.",
    "Kibla": "Smjer prema Kabi u Mekki.",
    "Kijam": "Stajanje u namazu.",
    "Kijamet": "Sudnji dan, kraj ovog svijeta i početak vječnog života.",
    "Kiraet": "Učenje Kur'ana, posebno tokom obavljanja namaza.",
    "Kitab": "Knjiga, često se misli na Kur'an ili druge objave.",
    "Kufr": "Nevjerovanje ili poricanje Allahove istine.",
    "Kur’an": "Posljednja Božija objava poslana cijelom čovječanstvu.",
    "Kurban": "Žrtva koja se kolje u ime Allaha radi približavanja Njemu.",
    "Lejletul-kadr": "Noć Sudbine, najvrednija noć u godini u mjesecu ramazanu.",
    "Lejletul-miradž": "Noć u kojoj je Poslanik, a.s., uzdignut do Allaha.",
    "Magrib": "Zapad, vrijeme zalaska sunca i akšam-namaza.",
    "Medresa": "Škola u kojoj se stječe srednje islamsko obrazovanje.",
    "Mehr": "Vjenčani dar koji muž daje supruzi.",
    "Mekruh": "Nešto što je pokuđeno i što je bolje izbjegavati.",
    "Mekruh tenzihen": "Lakši oblik pokuđenosti.",
    "Mekruh tahrimen": "Teži oblik pokuđenosti koji je blizu harama.",
    "Melek": "Duhovno biće stvoreno od svjetlosti koje sluša Allaha.",
    "Mendub": "Djelo koje je lijepo i pohvalno uraditi.",
    "Mevlud": "Rođenje Muhammeda, a.s., i svečanost tim povodom.",
    "Mezheb": "Pravna škola ili pravac u tumačenju propisa.",
    "Mezar": "Grob, mjesto ukopa umrle osobe.",
    "Mihrab": "Mjesto u džamiji koje pokazuje smjer kible.",
    "Mikat": "Mjesto na kojem hadžije oblače ihrame.",
    "Minber": "Uzvišeno mjesto u džamiji s kojeg imam drži hutbu.",
    "Miradž": "Putovanje Muhammeda, a.s., kroz nebeska prostranstva.",
    "Muallim/a": "Vjeroučitelj ili vjeroučiteljica u mektebu.",
    "Mubah": "Djelo koje je dozvoljeno i neutralno.",
    "Mudžiza": "Nadnaravna pojava kojom Allah potvrđuje poslanike.",
    "Mufsid": "Djelo koje kvari ili poništava ispravnost obreda.",
    "Muhaddis": "Učenjak koji se bavi izučavanjem hadisa.",
    "Muhadžir": "Iseljenik koji je radi vjere napustio svoj dom.",
    "Muftija": "Vjerski autoritet ovlašten za izdavanje fetvi.",
    "Mukabela": "Zajedničko učenje Kur'ana tokom ramazana.",
    "Muktedija": "Osoba koja klanja namaz prateći imama.",
    "Munafik": "Licemjer, osoba koja skriva nevjerstvo a pokazuje vjeru.",
    "Musafir": "Osoba koja se nalazi na putovanju.",
    "Mushaf": "Zapisani tekst cijelog Kur'ana u obliku knjige.",
    "Mustehab": "Djelo koje je lijepo i pohvalno činiti.",
    "Nifak": "Licemjerstvo, pretvaranje u vjeri.",
    "Nifas": "Krvarenje kod žena nakon porođaja.",
    "Nisab": "Određena količina imovine na koju se daje zekat.",
    "Nišan": "Nadgrobni spomenik specifičnog izgleda kod muslimana.",
    "Omer ibn Hattab": "Drugi pravedni halifa poznat po svojoj pravednosti.",
    "Osman ibn Affan": "Treći pravedni halifa poznat po darežljivosti.",
    "Rabb": "Gospodar, Stvoritelj i Održavatelj svega.",
    "Ramazan": "Deveti mjesec islamskog kalendara i mjesec posta.",
    "Resulullah": "Allahov Poslanik, naziv za Muhammeda, a.s.",
    "Rekat": "Jedan ciklus radnji u namazu.",
    "Rijaset": "Vrhovno tijelo i uprava Islamske zajednice.",
    "Ruku": "Pregibanje u namazu sa dlanovima na koljenima.",
    "Sabah": "Jutro, vrijeme svitanja i prvog dnevnog namaza.",
    "Sadakatul-fitr": "Milostinja koja se daje siromašnima uz ramazan.",
    "Saff": "Red klanjača koji stoje jedan do drugog.",
    "Safa i Merva": "Dva brežuljka u Mekki između kojih se kreću hadžije.",
    "Sahibi-uzur": "Osoba koja ima stalnu fizičku zapreku za obrede.",
    "Sahih": "Vjerodostojan i ispravan (hadis ili obred).",
    "Saj": "Užurbani hod između Safe i Merve.",
    "Salavat": "Molitva i blagoslov za Muhammeda, a.s.",
    "Sedžada": "Prostirač na kojem se obavlja namaz.",
    "Sedžda": "Spuštanje lica na tlo u namazu radi pokornosti Allahu.",
    "Sedždei-tilavet": "Sedžda koja se čini zbog određenih ajeta u Kur'anu.",
    "Sehur": "Obrok pred zoru kojim počinje dnevni post.",
    "Sehvi-sedžda": "Dvije sedžde na kraju namaza zbog nehoticne greške.",
    "Sifat": "Svojstvo ili osobina.",
    "Sifati-zatijje": "Allahova svojstva koja pripadaju samo Njemu.",
    "Sifati-subutijje": "Allahova svojstva koja se u tragovima nalaze kod stvorenja.",
    "Sira": "Životopis Muhammeda, a.s.",
    "Sufara": "Priručnik za učenje arapskog pisma i čitanja Kur'ana.",
    "Sunet": "Obrezivanje muške djece radi higijene i tradicije.",
    "Sunnet": "Sve što je Poslanik, a.s., radio, govorio ili preporučio.",
    "Sunnet muekkede": "Pritvrđeni sunnet koji je Poslanik stalno činio.",
    "Sunnet gajri muekkede": "Nepritvrđeni sunnet koji je Poslanik povremeno činio.",
    "Sura": "Poglavlje u Kur'anu kojih ima ukupno stotinu i četrnaest.",
    "Šart": "Uslov koji mora biti ispunjen za valjanost obreda.",
    "Šefaat": "Zauzimanje Poslanika, a.s., za vjernike na Sudnjem danu.",
    "Šehadet": "Svjedočenje da je samo Allah Bog i Muhammed Njegov poslanik.",
    "Šehid": "Vjernik koji je poginuo braneći vjeru ili domovinu.",
    "Šejh": "Učen čovjek ili duhovni vođa.",
    "Šerijat": "Islamski zakon utemeljen na Kur'anu i sunnetu.",
    "Širk": "Pripisivanje Allahu druga, najveći grijeh.",
    "Taharet": "Stanje potpune vjerske i fizičke čistoće.",
    "Tavaf": "Obilaženje oko Kabe sedam puta.",
    "Tedžvid": "Nauka o pravilnom učenju Kur'ana.",
    "Tefsir": "Nauka o tumačenju smisla kur’anskih ajeta.",
    "Tejemmum": "Čišćenje čistom zemljom kada nema vode.",
    "Tekbir": "Izgovaranje riječi 'Allahu ekber'.",
    "Tekbiri-tešrik": "Tekbiri koji se uče tokom Kurban-bajrama.",
    "Tespih": "Spominjanje i hvaljenje Allaha određenim riječima.",
    "Tevba": "Iskreno pokajanje Allahu za učinjene grijehe.",
    "Tevhid": "Vjerovanje u Allahovu jednoću.",
    "Ummet": "Zajednica svih muslimana svijeta.",
    "Umra": "Posjeta Kabi koja se obavlja izvan vremena hadža.",
    "Vadžib": "Vjerska obaveza koja je po rangu odmah ispod farza.",
    "Vakuf": "Trajna zadužbina u ime Allaha za opće dobro ljudi.",
    "Zekat": "Obavezno davanje dijela imovine siromašnima.",
    "Zikr": "Spominjanje Allaha riječima hvale i zahvale.",
    "Zuhr": "Podne, vrijeme drugog dnevnog namaza."
};