const https = require('https');
const fs = require('fs');
const path = require('path');

const BASE = 'https://mekteb.net';
const OUT = '/app/edu/assets/images';
const images = [
  "/edu/assets/images/abdeski_sarti.jpg",
  "/edu/assets/images/abdest1.jpg",
  "/edu/assets/images/adem_as.jpg",
  "/edu/assets/images/aksam_farz.jpg",
  "/edu/assets/images/aksam_namaz.jpg",
  "/edu/assets/images/aksam_sunnet.jpg",
  "/edu/assets/images/alkohol.jpg",
  "/edu/assets/images/alkohol2.jpg",
  "/edu/assets/images/alkohol3.jpg",
  "/edu/assets/images/alkohol_10.jpg",
  "/edu/assets/images/allahu_rabbi.jpg",
  "/edu/assets/images/amentu_billahi.jpg",
  "/edu/assets/images/arefat.jpg",
  "/edu/assets/images/asr.jpg",
  "/edu/assets/images/bajram_namaz.jpg",
  "/edu/assets/images/bajram_priprema.jpg",
  "/edu/assets/images/bajramsko_veselje.jpg",
  "/edu/assets/images/bedr.jpg",
  "/edu/assets/images/bejtul_mal.jpg",
  "/edu/assets/images/biljke_zivotinje.jpg",
  "/edu/assets/images/bosanski_jezik.jpg",
  "/edu/assets/images/bosna.jpg",
  "/edu/assets/images/bosna_hercegovina.jpg",
  "/edu/assets/images/bosnjak.jpg",
  "/edu/assets/images/braca_sestre.jpg",
  "/edu/assets/images/brak_porodica.jpg",
  "/edu/assets/images/briga_stariji.jpg",
  "/edu/assets/images/cestitost.jpg",
  "/edu/assets/images/cistoca.jpg",
  "/edu/assets/images/covjek.jpg",
  "/edu/assets/images/dan_dzamija.jpg",
  "/edu/assets/images/desna_strana.jpg",
  "/edu/assets/images/dinski_sarti.jpg",
  "/edu/assets/images/djetinjstvo.jpg",
  "/edu/assets/images/dobrota.jpg",
  "/edu/assets/images/dova_poslije_ezana.jpg",
  "/edu/assets/images/dova_poslije_jela.jpg",
  "/edu/assets/images/dova_za_znanje.jpg",
  "/edu/assets/images/dove.jpg",
  "/edu/assets/images/droga.jpg",
  "/edu/assets/images/droga1.jpg",
  "/edu/assets/images/drogerija.jpg",
  "/edu/assets/images/duhan.jpg",
  "/edu/assets/images/dzemat.jpg",
  "/edu/assets/images/dzenaza.jpg",
  "/edu/assets/images/dzennet_dzehennem.jpg",
  "/edu/assets/images/dzini_sejtani.jpg",
  "/edu/assets/images/dzuma_namaz.jpg",
  "/edu/assets/images/ekologija.jpg",
  "/edu/assets/images/elif_lam_mim.jpg",
  "/edu/assets/images/estagfirullah.jpg",
  "/edu/assets/images/et_tehijatu.jpg",
  "/edu/assets/images/euzubilla.jpg",
  "/edu/assets/images/euzubilla2.jpg",
  "/edu/assets/images/ezan_munara.jpg",
  "/edu/assets/images/farzovi.jpg",
  "/edu/assets/images/fatiha.jpg",
  "/edu/assets/images/fil.jpg",
  "/edu/assets/images/gajb.jpg",
  "/edu/assets/images/grijeh.jpg",
  "/edu/assets/images/gusul.jpg",
  "/edu/assets/images/hadiske_zbirke.jpg",
  "/edu/assets/images/hadz.jpg",
  "/edu/assets/images/halal_haram.jpg",
  "/edu/assets/images/halife.jpg",
  "/edu/assets/images/hasbi_rabbi.jpg",
  "/edu/assets/images/hidzab1.jpg",
  "/edu/assets/images/hidzama.jpg",
  "/edu/assets/images/hidzra.jpg",
  "/edu/assets/images/horoskop.jpg",
  "/edu/assets/images/humeze.jpg",
  "/edu/assets/images/husna.jpg",
  "/edu/assets/images/ibrahim.jpg",
  "/edu/assets/images/iftar.jpg",
  "/edu/assets/images/iftitahi_tekbir.jpg",
  "/edu/assets/images/ikamet.jpg",
  "/edu/assets/images/ikindija_namaz.jpg",
  "/edu/assets/images/imanski_sarti.jpg",
  "/edu/assets/images/internet.jpg",
  "/edu/assets/images/isa.jpg",
  "/edu/assets/images/ishrana.jpg",
  "/edu/assets/images/iskrenost.jpg",
  "/edu/assets/images/iskrenost_saosjecajnost.jpg",
  "/edu/assets/images/islamski_sarti.jpg",
  "/edu/assets/images/istina.jpg",
  "/edu/assets/images/istinoljubivost.jpg",
  "/edu/assets/images/iz_bih.jpg",
  "/edu/assets/images/izvrsavanje_duznosti.jpg",
  "/edu/assets/images/jacija_namaz.jpg",
  "/edu/assets/images/jahanje.jpg",
  "/edu/assets/images/jedan.jpg",
  "/edu/assets/images/jedan1.jpg",
  "/edu/assets/images/kaba1.jpg",
  "/edu/assets/images/kaba_view.jpg",
  "/edu/assets/images/kader.jpg",
  "/edu/assets/images/karia.jpg",
  "/edu/assets/images/kibla.jpg",
  "/edu/assets/images/kijam_z.jpg",
  "/edu/assets/images/kipovi.jpg",
  "/edu/assets/images/kiraet2.jpg",
  "/edu/assets/images/kitabi.jpg",
  "/edu/assets/images/knjige_suhufi.jpg",
  "/edu/assets/images/kocka.jpg",
  "/edu/assets/images/komsije.jpg",
  "/edu/assets/images/kuds.jpg",
  "/edu/assets/images/kufr.jpg",
  "/edu/assets/images/kultura.jpg",
  "/edu/assets/images/kunut_dova.jpg",
  "/edu/assets/images/kuran.jpg",
  "/edu/assets/images/kurban.jpg",
  "/edu/assets/images/leheb.jpg",
  "/edu/assets/images/lekad_dzaekum.jpg",
  "/edu/assets/images/licemjer.jpg",
  "/edu/assets/images/lijepa_imena.jpg",
  "/edu/assets/images/lijepa_rijec.jpg",
  "/edu/assets/images/masallah.jpg",
  "/edu/assets/images/medina.jpg",
  "/edu/assets/images/mekruhi.jpg",
  "/edu/assets/images/mekteb_dzamija.jpg",
  "/edu/assets/images/mekteb_prvi_dan.jpg",
  "/edu/assets/images/mekteb_znanje.jpg",
  "/edu/assets/images/meleki.jpg",
  "/edu/assets/images/mesh.jpg",
  "/edu/assets/images/mevlud.jpg",
  "/edu/assets/images/mevlud2.jpg",
  "/edu/assets/images/miradz.jpg",
  "/edu/assets/images/mirza_zuri.jpg",
  "/edu/assets/images/mrznja.jpg",
  "/edu/assets/images/mubarek_dani.jpg",
  "/edu/assets/images/mubarek_noci.jpg",
  "/edu/assets/images/mudzize.jpg",
  "/edu/assets/images/mukellefin.jpg",
  "/edu/assets/images/munara.jpg",
  "/edu/assets/images/musa.jpg",
  "/edu/assets/images/nafila_namaz.jpg",
  "/edu/assets/images/namaska_dova.jpg",
  "/edu/assets/images/namaska_vremena.jpg",
  "/edu/assets/images/namaski_sarti.jpg",
  "/edu/assets/images/namaz_bolesnika.jpg",
  "/edu/assets/images/namaz_cuva.jpg",
  "/edu/assets/images/namaz_propisi.jpg",
  "/edu/assets/images/namaz_putnik_bolesnik.jpg",
  "/edu/assets/images/naocale.jpg",
  "/edu/assets/images/nasa_vjera.jpg",
  "/edu/assets/images/nasr.jpg",
  "/edu/assets/images/nemoral.jpg",
  "/edu/assets/images/neprijateljstvo.jpg",
  "/edu/assets/images/nijjet.jpg",
  "/edu/assets/images/nova_godina.jpg",
  "/edu/assets/images/nuh.jpg",
  "/edu/assets/images/odabrane_zene.jpg",
  "/edu/assets/images/odjeca.jpg",
  "/edu/assets/images/ogovaranje.jpg",
  "/edu/assets/images/oholost.jpg",
  "/edu/assets/images/oprostajni_hadz.jpg",
  "/edu/assets/images/orijentacija.jpg",
  "/edu/assets/images/pet_namaza.jpg",
  "/edu/assets/images/poboznost.jpg",
  "/edu/assets/images/podne_namaz.jpg",
  "/edu/assets/images/ponasanje_drustvo.jpg",
  "/edu/assets/images/ponasanje_jela.jpg",
  "/edu/assets/images/porodica.jpg",
  "/edu/assets/images/porodica1.jpg",
  "/edu/assets/images/poslanici.jpg",
  "/edu/assets/images/poslanici_kuran.jpg",
  "/edu/assets/images/poslanik.jpg",
  "/edu/assets/images/posljedice_grijeha.jpg",
  "/edu/assets/images/post.jpg",
  "/edu/assets/images/post1.jpg",
  "/edu/assets/images/poznati_alimi.jpg",
  "/edu/assets/images/preseljenje.jpg",
  "/edu/assets/images/prevara.jpg",
  "/edu/assets/images/prijateljstvo.jpg",
  "/edu/assets/images/priroda.jpg",
  "/edu/assets/images/prispijevanje.jpg",
  "/edu/assets/images/propusteni_namaz.jpg",
  "/edu/assets/images/prozivljenje.jpg",
  "/edu/assets/images/rabbi_jessir.jpg",
  "/edu/assets/images/rad.jpg",
  "/edu/assets/images/radne_navike.jpg",
  "/edu/assets/images/ramazanski_bajram.jpg",
  "/edu/assets/images/rijaset.jpg",
  "/edu/assets/images/rodbina.jpg",
  "/edu/assets/images/roditelji.jpg",
  "/edu/assets/images/ruknovi1.jpg",
  "/edu/assets/images/ruknovi2.jpg",
  "/edu/assets/images/sabah_namaz.jpg",
  "/edu/assets/images/sabah_sunnet_potiranje.png",
  "/edu/assets/images/sabah_sunnet_rekat1_kijam.png",
  "/edu/assets/images/sabah_sunnet_rekat1_ruku.png",
  "/edu/assets/images/sabah_sunnet_rekat1_sedzda1.png",
  "/edu/assets/images/sabah_sunnet_rekat1_sedzda2.png",
  "/edu/assets/images/sabah_sunnet_rekat1_sjedenje.png",
  "/edu/assets/images/sabah_sunnet_rekat1_tekbir.png",
  "/edu/assets/images/sabah_sunnet_rekat1_vracanje.png",
  "/edu/assets/images/sabah_sunnet_rekat2_kijam.png",
  "/edu/assets/images/sabah_sunnet_selam_desno.png",
  "/edu/assets/images/sabah_sunnet_selam_lijevo.png",
  "/edu/assets/images/sabah_sunnet_sjedenje.png",
  "/edu/assets/images/sadaka.jpg",
  "/edu/assets/images/sahibi_uzur.jpg",
  "/edu/assets/images/salavati.jpg",
  "/edu/assets/images/samilost.jpg",
  "/edu/assets/images/sehadet5.jpg",
  "/edu/assets/images/sehvi_sedzda.jpg",
  "/edu/assets/images/selam.jpg",
  "/edu/assets/images/selam1.jpg",
  "/edu/assets/images/sifatus_subutijje.jpg",
  "/edu/assets/images/sifatuz_zatijje.jpg",
  "/edu/assets/images/sirat.jpg",
  "/edu/assets/images/skromnost.jpg",
  "/edu/assets/images/skrtost.jpg",
  "/edu/assets/images/slon.jpg",
  "/edu/assets/images/sport.jpg",
  "/edu/assets/images/srednji_put.jpg",
  "/edu/assets/images/sta_kvari_abdest.jpg",
  "/edu/assets/images/sta_kvari_namaz.jpg",
  "/edu/assets/images/stariji1.jpg",
  "/edu/assets/images/streljastvo.jpg",
  "/edu/assets/images/strpljivost.jpg",
  "/edu/assets/images/stvoritelj.jpg",
  "/edu/assets/images/subhaneke.jpg",
  "/edu/assets/images/sudnji_dan.jpg",
  "/edu/assets/images/suhufi.jpg",
  "/edu/assets/images/sunneti.jpg",
  "/edu/assets/images/sura_el_ihlas.jpg",
  "/edu/assets/images/sura_el_kafirun.jpg",
  "/edu/assets/images/sura_el_kevser.jpg",
  "/edu/assets/images/sura_el_kurejsh.jpg",
  "/edu/assets/images/sura_el_maun.jpg",
  "/edu/assets/images/sura_en_nas.jpg",
  "/edu/assets/images/sura_felek.jpg",
  "/edu/assets/images/sura_leheb_ornament.png",
  "/edu/assets/images/svadba_odjeca.jpg",
  "/edu/assets/images/sve_vidi.jpg",
  "/edu/assets/images/tejemmum.jpg",
  "/edu/assets/images/tejemum.jpg",
  "/edu/assets/images/tekasur.jpg",
  "/edu/assets/images/tekvin.jpg",
  "/edu/assets/images/teravih_namaz.jpg",
  "/edu/assets/images/teski_grijesi.jpg",
  "/edu/assets/images/tevba.jpg",
  "/edu/assets/images/ucenje2.jpg",
  "/edu/assets/images/ucenje_kuran.jpg",
  "/edu/assets/images/ulazak_izlazak.jpg",
  "/edu/assets/images/urednost.jpg",
  "/edu/assets/images/ustanove.jpg",
  "/edu/assets/images/uvodna.jpg",
  "/edu/assets/images/vadzibi.jpg",
  "/edu/assets/images/vaktija_app.jpg",
  "/edu/assets/images/vakuf.jpg",
  "/edu/assets/images/vakuf1.jpg",
  "/edu/assets/images/ve_bil_kaderi.jpg",
  "/edu/assets/images/ve_melaiketihi.jpg",
  "/edu/assets/images/veliki_grijesi.jpg",
  "/edu/assets/images/vjecnost.jpg",
  "/edu/assets/images/voda.jpg",
  "/edu/assets/images/vrste_namaza.jpg",
  "/edu/assets/images/zdravlje.jpg",
  "/edu/assets/images/zekat.jpg",
  "/edu/assets/images/zenidba.jpg",
  "/edu/assets/images/zikr.jpg",
  "/edu/assets/images/čistoća.jpg"
];

fs.mkdirSync(OUT, { recursive: true });
fs.mkdirSync(path.join(OUT, 'pitanja'), { recursive: true });

let done = 0, errors = 0;

function download(imgPath) {
  return new Promise((resolve) => {
    const url = BASE + imgPath;
    const filename = path.basename(imgPath);
    const subdir = imgPath.includes('/pitanja/') ? 'pitanja' : '';
    const dest = path.join(OUT, subdir, filename);
    if (fs.existsSync(dest)) { done++; process.stdout.write('.'); return resolve(); }
    const file = fs.createWriteStream(dest);
    https.get(url, { rejectUnauthorized: false }, (res) => {
      if (res.statusCode !== 200) {
        file.close();
        try { fs.unlinkSync(dest); } catch(e) {}
        errors++;
        process.stdout.write('x');
        return resolve();
      }
      res.pipe(file);
      file.on('finish', () => { file.close(); done++; process.stdout.write('.'); resolve(); });
    }).on('error', () => { errors++; process.stdout.write('x'); resolve(); });
  });
}

(async () => {
  console.log('Preuzimam ' + images.length + ' slika...');
  for (let i = 0; i < images.length; i += 5) {
    const batch = images.slice(i, i + 5);
    await Promise.all(batch.map(download));
  }
  console.log('
Gotovo! Preuzeto: ' + done + ' | Greske: ' + errors);
  console.log('Provjera: ' + fs.readdirSync(OUT).length + ' fajlova');
})();
